update mypy version
PolicyEngine/policyengine-core pull request #246
Opened 2024-08-10 20:17 UTC by SeanAverS

## What's changed

in `setup.py`, update mypy version from `0.991` to `1.11.1`

## What this fixes and how it's fixed
- Fixes #243

2024-08-10 20:21 UTC, MaxGhenis requested changes
Thanks! Did this pass tests locally?

2024-08-10 20:21 UTC, MaxGhenis commented on setup.py
> +    "mypy==1.11.1",
We generally only pin to a specific version if an incompatibility arises, otherwise the current major
```suggestion
    "mypy<2",
```

2024-08-10 20:21 UTC, MaxGhenis commented
Please also populate changelog_entry.yaml (see other PRs)

2024-08-13 19:26 UTC, MaxGhenis commented
changelog_entry.yaml not changelog.yaml

2024-08-13 19:36 UTC, SeanAverS commented
@MaxGhenis thank you for your patience 🙏

2024-08-13 19:43 UTC, MaxGhenis commented
Please do not edit changelog (we automate that)

2024-08-14 03:45 UTC, MaxGhenis requested changes
please match the format of changelog_entry.yaml from other merged prs to address the CI failure

2024-08-16 05:30 UTC, MaxGhenis requested changes

2024-08-16 05:30 UTC, MaxGhenis commented on changelog_entry.yaml
> +- bump: minor
```suggestion
- bump: patch
```
Since it doesn't introduce new functionality

2024-08-16 05:30 UTC, MaxGhenis commented on changelog_entry.yaml
> +    - change mypy version from 1.11.1 to <2
```suggestion
      - change mypy version from 1.11.1 to <2

```

2024-08-17 19:28 UTC, MaxGhenis approved these changes

2024-08-17 19:28 UTC, merged